# Generated by Django 3.1.5 on 2021-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_at', models.DateField(default=None, help_text='预约时间')),
                ('meal_type', models.SmallIntegerField(default=None, help_text='用餐时间，早餐：1；午餐：2：晚餐：3')),
                ('wx_id', models.IntegerField(default=None, help_text='微信id')),
                ('is_delete', models.SmallIntegerField(default=0, help_text='已取消：0否，1是')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'ordering': ('appointment_at',),
            },
        ),
    ]
